version: '2'
services:
  newoapp24-app:
    image: newoapp24
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://newoapp24-postgresql:5432/NewoApp24
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  newoapp24-postgresql:
    extends:
      file: postgresql.yml
      service: newoapp24-postgresql
